# This file was generated by GoReleaser. DO NOT EDIT.
cask "quick-branch" do
  postflight do
    system_command "/usr/bin/xattr",
      args: ["-dr", "com.apple.quarantine", "#{staged_path}"],
      sudo: false
  end

  name "quick-branch"
  desc "Quick branch creation tool for Linear issues"
  homepage "https://github.com/rangoons/quick-branch"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "quick-branch"

  on_macos do
    on_intel do
      url "https://github.com/Rangoons/quick-branch/releases/download/v#{version}/quick-branch_#{version}_darwin_amd64.tar.gz"
      sha256 "69789bd4b3e4aa5412c03455bcfa671a143459b76ab9c1e73ad5f2ed32dacf8f"
    end
    on_arm do
      url "https://github.com/Rangoons/quick-branch/releases/download/v#{version}/quick-branch_#{version}_darwin_arm64.tar.gz"
      sha256 "5dda3e9c50633f80021c00bbec0d8ced6ccba5047f82e607a658369d3a75b9de"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Rangoons/quick-branch/releases/download/v#{version}/quick-branch_#{version}_linux_amd64.tar.gz"
      sha256 "c2ba8966fb892740eb06eff4cfb91b7e2e581954574bac5c6e106177025c876a"
    end
    on_arm do
      url "https://github.com/Rangoons/quick-branch/releases/download/v#{version}/quick-branch_#{version}_linux_arm64.tar.gz"
      sha256 "7615a37903cf43a50b88a15fb15c346e3f88e7272aeaea4c2a4a7c45f980bc4e"
    end
  end

  # No zap stanza required
end
