# This file was generated by GoReleaser. DO NOT EDIT.
cask "quick-branch" do
  postflight do
    system_command "/usr/bin/xattr",
      args: ["-dr", "com.apple.quarantine", "#{staged_path}"],
      sudo: false
  end

  name "quick-branch"
  desc "Quick branch creation tool for Linear issues"
  homepage "https://github.com/rangoons/quick-branch"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "quick-branch"

  on_macos do
    on_intel do
      url "https://github.com/Rangoons/quick-branch/releases/download/v#{version}/quick-branch_#{version}_darwin_amd64.tar.gz"
      sha256 "d350c10bfb9ab6c260940d9615fb4259cf05e12dffb4541561ae0ff44dcc687d"
    end
    on_arm do
      url "https://github.com/Rangoons/quick-branch/releases/download/v#{version}/quick-branch_#{version}_darwin_arm64.tar.gz"
      sha256 "b1c4c6b196d3390da8f86379a55f37001d6ad988da173cb9c4801f3e5b27b3bd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Rangoons/quick-branch/releases/download/v#{version}/quick-branch_#{version}_linux_amd64.tar.gz"
      sha256 "e04f3e1584f9c2f8b07aaaed96317911539ba55ade1fe999e9eaf570cc0ed041"
    end
    on_arm do
      url "https://github.com/Rangoons/quick-branch/releases/download/v#{version}/quick-branch_#{version}_linux_arm64.tar.gz"
      sha256 "b194aebb322448ed5353acf5b32b1747925abbe8318a9ac405fb6365e75b80c9"
    end
  end

  # No zap stanza required
end
