# This file was generated by GoReleaser. DO NOT EDIT.
cask "quick-branch" do
  postflight do
    system_command "/usr/bin/xattr",
      args: ["-dr", "com.apple.quarantine", "#{staged_path}"],
      sudo: false
  end

  name "quick-branch"
  desc "Quick branch creation tool for Linear issues"
  homepage "https://github.com/rangoons/quick-branch"
  version "0.2.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "quick-branch"

  on_macos do
    on_intel do
      url "https://github.com/Rangoons/quick-branch/releases/download/v#{version}/quick-branch_#{version}_darwin_amd64.tar.gz"
      sha256 "c2cb0f3cb7e84c54343e3ebfe3e58aa9544b7439a5bff58c41932bdc128cf626"
    end
    on_arm do
      url "https://github.com/Rangoons/quick-branch/releases/download/v#{version}/quick-branch_#{version}_darwin_arm64.tar.gz"
      sha256 "15d1d375580be7380a2a93a89b00c26d37cd8e02a8753d2f54e64f2e5fba66af"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Rangoons/quick-branch/releases/download/v#{version}/quick-branch_#{version}_linux_amd64.tar.gz"
      sha256 "f95ee7d180c4b9b7c043bfc9390e383ec5e3e6e9b84456e7b3dacf21593fc36c"
    end
    on_arm do
      url "https://github.com/Rangoons/quick-branch/releases/download/v#{version}/quick-branch_#{version}_linux_arm64.tar.gz"
      sha256 "5ec000d93afc572d304f8393bf4227acbe3a3f47db399791bd1cd2a48956b23e"
    end
  end

  # No zap stanza required
end
